// /utils/generateReportHTML.js

export function generateReportHTML(data) {
    const successRate = ((data.passed / data.totalTests) * 100).toFixed(2);
  
    return `
    <html>
      <head>
        <meta charset="UTF-8" />
        <style>
          body {
            font-family: Arial, sans-serif;
            padding: 24px;
            color: #333;
          }
  
          h1 {
            text-align: center;
          }
  
          .summary {
            display: flex;
            justify-content: space-between;
            margin: 20px 0;
          }
  
          .card {
            border: 1px solid #ddd;
            padding: 12px;
            border-radius: 8px;
            width: 30%;
            text-align: center;
          }
  
          .success { color: green; }
          .fail { color: red; }
  
          table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
          }
  
          th, td {
            border: 1px solid #ddd;
            padding: 10px;
            font-size: 14px;
          }
  
          th {
            background: #f5f5f5;
          }
  
          .footer {
            margin-top: 30px;
            font-size: 12px;
            text-align: center;
            color: #888;
          }
        </style>
      </head>
  
      <body>
        <h1>API Test Report</h1>
  
        <p><strong>Generated on:</strong> ${new Date().toLocaleString()}</p>
  
        <div class="summary">
          <div class="card">
            <h3>Total</h3>
            <p>${data.totalTests}</p>
          </div>
          <div class="card">
            <h3 class="success">Passed</h3>
            <p>${data.passed}</p>
          </div>
          <div class="card">
            <h3 class="fail">Failed</h3>
            <p>${data.failed}</p>
          </div>
        </div>
  
        <p><strong>Success Rate:</strong> ${successRate}%</p>
  
        ${
          data.chartImage
            ? `<img src="${data.chartImage}" style="width:100%; margin:20px 0;" />`
            : ''
        }
  
        <table>
          <thead>
            <tr>
              <th>Name</th>
              <th>Method</th>
              <th>Endpoint</th>
              <th>Status</th>
              <th>Expected</th>
            </tr>
          </thead>
          <tbody>
            ${data.tests
              .map(
                (t) => `
                <tr>
                  <td>${t.name}</td>
                  <td>${t.method}</td>
                  <td>${t.endpoint}</td>
                  <td class="${t.actualStatus < 400 ? 'success' : 'fail'}">
                    ${t.actualStatus}
                  </td>
                  <td>${t.expectedStatus}</td>
                </tr>
              `
              )
              .join('')}
          </tbody>
        </table>
  
        <div class="footer">
          Generated by API Test Tool
        </div>
      </body>
    </html>
    `;
  }